name: Publish

on:
  release:
    types: [released, prereleased]
jobs:
  build:
    env: # Or as an environment variable
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.1.20452.10
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Pack
        run: dotnet pack --configuration Release -p:Version=${{ github.event.release.tag_name }}
      - name: Push
        run: dotnet nuget push "**/Release/*.nupkg" --source "github" --skip-duplicate
